# Generated by Django 4.0 on 2022-07-01 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0002_alter_category_options_donation_is_taken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('is_user_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['pick_up_date', 'pick_up_time']},
        ),
    ]
