# Generated by Django 4.0 on 2022-09-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_extenduser_alter_donation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
